### ISSUE TITLE
Copy replaces \n with spaces

### ISSUE THREAD

**Issue by 7AC** [mobile-shell/mosh#820] opened 2016-11-01 20:01 UTC
When copy/pasting via mouse on macOS, in some cases `\n` seems to get replaced by spaces. This seem to happen across different versions of macOS and different terminal apps, starting with `mosh-1.2.6`. Downgrading to `mosh-1.2.5` or switching to `ssh` seems to solve the issue (for now, couldn't find a reproducible/narrow case for this).

**Comment by cgull** [comment] 2016-11-01 20:40
I/we know about this, but yes, it's difficult to reproduce and doesn't occur often for me, and I haven't been able to pin it down.  I recently discovered some issues with how we handle updates involving scrolling (among other things), fixing those might also fix this. ^L sometimes but not always clears the bad screen state.

**Comment by tsuna** [comment] 2016-11-01 21:07
I've experienced this issue fairly regularly since 1.2.6 as well, and I use tmux on the remote end of my mosh sessions, if that helps anything to reproduce the bug.

**Comment by tsuna** [comment] 2016-11-01 21:30
tmux 2.3 on macOS on the client side, tmux 1.8 on Linux on the server side.  `Terminal.app` as the terminal emulator.

**Comment by ctbrownx** [comment] 2016-11-02 00:01
I've seen this as well.

Mac OS X 10.11.6 using Terminal.app
Mosh 1.2.6 on Linux server and Mac sides.
Tmux 2.2 on Linux server side.

Happens almost all the time when copying and pasting multiple lines of text (usually into vim).

**Comment by 7AC** [comment] 2016-11-02 04:16
Mine are:

client:
- macOS 10.12.1
- Terminal 2.7.1
- mosh 1.2.6
- OpenSSH_7.2p2, LibreSSL 2.4.1

server:
- Linux 3.18.28
- mosh 1.2.4
- OpenSSH_6.6.1p1, OpenSSL 1.0.2h-fips

Thanks for looking into this.

**Comment by zi0r** [comment] 2016-11-06 04:51
I've seen this with irssi running in screen/SecureCRT under OSX.

TERM is xterm-256color
UTF8
mosh 1.2.6 client w/mosh 1.2.5 server

Selecting multiple lines of text in irssi resulted in me pasting a single line with lots of spaces where a line return should have been.

**Comment by cgull** [comment] 2016-11-17 07:01
See #830 for what I believe is the fix for this.  I think you'll need to fix both client and server to resolve this problem (where the fix is this code, or Mosh 1.2.5, but not not Mosh 1.2.6).

**Comment by Ghosthree3** [comment] 2017-01-27 00:45
Experiencing this right now when I try to copy text out of weechat(1.7)'s bare display inside tmux(2.3) using mosh(1.2.6) inside urxvt(9.22). Frequently. Like every time I copy a block of text 2-3 lines always have it.

**Comment by johnhawkinson** [comment] 2017-03-26 20:03
I continue to see this problem with a mosh 1.3.0 client against a mosh 1.3.0-rc2 server inside Terminal.app. I don't have a clear test case for it, and I've kind of learned to live with it (liberal application of `M-x delete-trailing-whitespace`).

**Comment by cgull** [comment] 2017-03-27 02:22
I think I've gotten a little mixed up here.  I think there may be two bugs at play:
* Copy/paste results in multiple lines padded to the width of the terminal and not separated by newlines, so that they paste as a single line into the destination.  That bug is fixed in #830.
* Copy/paste results in multiple lines padded to the width of the terminal, but separated by newlines, so that they paste as multiple lines into the destination with unexpected whitespace at the end of each line.  I still haven't reproduced that.

Which are people seeing here?  (Or are people seeing something else?)

**Comment by johnhawkinson** [comment] 2017-03-27 02:24
The latter. (Is this duplicative of #856?)

**Comment by cgull** [comment] 2017-03-27 02:41
Maybe.  The first pastebin there seems to be a mix of bugs 1 and 2.

I still can't reproduce this.

**Comment by johnhawkinson** [comment] 2017-03-27 02:45
So, the primary place I see this is in mutt inside screen.
I don't see it copying from, e.g., the shell prompt in the same screen.

I'm not sure what an appropriate test tool for curses-using apps inside screen is...I realize mutt is a complicated application. (That's part of why I haven't tried to report this previously...)
Err $TERM inside screen is `screen` and outside screen is `xterm`.

**Comment by andersk** [comment] 2017-03-27 02:53
@johnhawkinson One thing you could try to do is run `mutt` inside `screen` inside `script` inside `mosh`. If you can reproduce the problem that way, then you should also be able to reproduce it by `cat`ing (some truncation of) the resulting `typescript` file inside `mosh` with the same terminal size. Once we have a reproducing `typescript` file, it should be much easier to systematically figure out where the problem is. I realize this may be easier said than done, though.

**Comment by johnhawkinson** [comment] 2017-03-27 03:02
That seems straightforward enough.
https://gist.github.com/7f248e91e632cc5b3ef417deaa7aafb2

80x48 terminal, reproduces with `cat`.

**Comment by andersk** [comment] 2017-03-27 03:22
@johnhawkinson Perfect, I can confirm that your `typescript` file gives different copy-and-paste results from an 80×48 gnome-terminal, outside and inside `mosh`:

```diff
--- outside
+++ inside
@@ -23,11 +23,9 @@
 bUoWAl                                                                          
         /NhZ4lZH5WdP1S5XAARJRXioV6VneROmTnc5FueafcnO0f/+KeN0Dt1CwUhoCRMwIak3HFwt
 tKDvCH                                                                          
-        w=                                                                      
-                                                                                
+        w=                                                                                                                                                      
 @johnhawkinson One thing you could try to do is run `mutt` inside `screen`      
-inside `script` inside `mosh`. If you can reproduce the problem that way, then  
-you should also be able to reproduce it by `cat`ing (some truncation of) the    
+inside `script` inside `mosh`. If you can reproduce the problem that way, then  you should also be able to reproduce it by `cat`ing (some truncation of) the    
 resulting `typescript` file inside `mosh` with the same terminal size. Once we  
 have a reproducing `typescript` file, it should be much easier to systematically
 figure out where the problem is. I realize this may be easier said than done,   
```

**Comment by cgull** [comment] 2017-03-27 03:33
I have managed to reproduce the second bug (spaces with newlines) viewing mail in `mutt` in `screen` in `mosh` from master in OS X 10.12.3 Terminal.  There, I get *all* lines being padded to 80 columns.  This doesn't happen with iTerm2 3.1.beta.2, or with tmux.

**Comment by cgull** [comment] 2017-03-27 04:37
So, @johnhawkinson's test case is producing spaces-no-newlines for me (with OS X Terminal) and @andersk, not the second bug.  @johnhawkinson, can you produce a diff or two paste outputs, like @andersk?

My best guess so far, though this seems at least partly incorrect for @andersk:
* You do something before running Mutt that produces some lines that wrap.
* You start Mutt.  It does not clear the whole screen with `ESC [ H ESC [ J`, instead it redraws the entire frame buffer with spaces.
* You view a message in Mutt.  It draws each line of the headers in the message by drawing 80 columns of text and/or spaces, repositioning the cursor with `ESC [ n ; n; H` after each line.  (For the *body* of the message, it mostly draws with `CR NL`, though.)
* Mosh takes this output as not having any signals about what to do with wrap at the end of line.  So any pre-existing wrap bits from pre-Mutt display remain while you're using Mutt, and influence copy pasta.

I regard output that writes `CR NL`, or output that clears to end of line, as signaling that the wrap status for that line should be reset.  Output that writes text past column 80 without any positioning controls should set wrap status.  There's some subtlety that I missed in my rewrite of the display code.  This bug is different from the prior line-wrapping bug.

Mutt is an ancient piece of code which might predate the idea of wrapping text output nicely for `xterm` and later terminal emulators, which may play some part in this.

**Comment by andersk** [comment] 2017-03-27 04:46
@cgull You seem to be right. If I run `reset; cat mosh-mutt.2.typescript`, there is no difference in the copy-paste output from inside and outside.

**Comment by johnhawkinson** [comment] 2017-03-27 04:50
I do not see a difference cat-ing my testcase in any of a) remote screen inside mosh b) remote ssh c) local. All inside Terminal.app (10.10.5)

> So, @johnhawkinson's test case is producing spaces-no-newlines for me (with OS X Terminal) and @andersk, not the second bug

In all cases, I get newlines and spaces. @cgull, you're saying you get spaces but not newlines? I cannot account for that, it seems odd.

I cat the test case, copy/paste into an Aqua Emacs, and save to a file. Then I `cat -vet` that saved file (in a terminal wider than 80 cols to account for the `$`) and I get:

```
pb3:tmp jhawk$ cat -vet /tmp/outside
X-GitHub-Sender: andersk                                                        $
X-GitHub-Recipient: johnhawkinson                                               $
X-GitHub-Reason: mention                                                        $
X-GitHub-Recipient-Address: jhawk@mit.edu                                       $
X-SG-EID:                                                                       $
DNW3zPVfWJz9Df/vXMX/yVeWyV5e8hErQwP8julertYOQd2aAovV/IpEk7ISeOA+EMzDrui7Z6vuyt  $
        PY76iXE2Wp53VK+fFTRhXV7tnDyXPvi0zUpOI3WACNaxAeIRVW8R1qFXlCTuXQFByzF/UBWv$
bUoWAl                                                                          $
        /NhZ4lZH5WdP1S5XAARJRXioV6VneROmTnc5FueafcnO0f/+KeN0Dt1CwUhoCRMwIak3HFwt$
tKDvCH                                                                          $
        w=                                                                      $
                                                                                $
@johnhawkinson One thing you could try to do is run `mutt` inside `screen`      $
inside `script` inside `mosh`. If you can reproduce the problem that way, then  $
you should also be able to reproduce it by `cat`ing (some truncation of) the    $
resulting `typescript` file inside `mosh` with the same terminal size. Once we  $
have a reproducing `typescript` file, it should be much easier to systematically$
figure out where the problem is. I realize this may be easier said than done,   $
though.                                                                         $
```

**Comment by andersk** [comment] 2017-03-27 05:03
Hmm, I think there’s still some evidence of a Mosh bug here, though it may be in the opposite direction. I do get different copy-and-paste output from

`reset; sh -c 'reset; printf "%5000s" ""; cat mosh-mutt.2.typescript; sleep 999'`

vs.

`reset; mosh localhost -- sh -c 'reset; printf "%5000s" ""; cat mosh-mutt.2.typescript; sleep 999'`

in that I see spaces-and-no-newlines without `mosh` while I see spaces-and-newlines with `mosh`.

**Comment by cgull** [comment] 2017-03-27 05:33
@johnhawkinson, that's what I get with Terminal.app-- all lines padded with spaces to the terminal width.  (I said before that @andersk and I were getting similar things, but I was using iTerm2 there, and typo-ed.)  Also, when did this problem appear for you?

@andersk, there's definitely a bug/regression here, it's just more subtle than the last one.

more tomorrow.

**Comment by johnhawkinson** [comment] 2017-03-27 13:32
Oops, I screwed up earlier.
Anders asked for:

> run `mutt` inside `screen` inside `script` inside `mosh`.

That's not what I did. The above file was from `mutt` inside `script` inside `screen` inside `mosh`, so it captured what `mut`t sent to `screen`, not what `screen` sent to `mosh`. Sorry.

Here is what was originally requested, capturing what `screen` sends to `mosh`:
https://gist.github.com/bb3d37a4abc4a6af6bad832670611b56

The final screen's result is still space-padded for the headers and not for the body, although it's just plain text+padding+CR+LF with a few SGR renditions scattered throughout, rather than cursor-positioning.

>  Also, when did this problem appear for you?

Oh, this problem has been with me for years, I think the entire time I've used mosh. It's annoying but worth the trade-off.

However I did some more tests, and I am more confused/embarrassed:
Running straight-up `Terminal.app `-> `ssh` -> `mutt` (no `mosh`) seems to be giving me these same whitespace pasting problems, which is not at all what I recall happening.  I'm not sure what to make
of this, but it certainly points the finger at `mut`t, not `mosh`. On the other hand, I'm certain I didn't used to have this problem. Of course, back then it would have been a different build of mutt, possibly with `slang` instead of `ncurses` or something, I don't know. Probably other changes. 
Ugh.

I believe I have seen some non-mutt cases (although at the moment I'm a lot less sure of the things I thought I knew), but they are (surprise) not as trivially reproducible. So there's that.

At least I can hang on to using `script` as a tool and  maybe that will let me capture something useful going forward.

**Comment by cgull** [comment] 2017-03-27 16:40
@johnhawkinson, it might not be (only) a change in Mutt causing you grief, `Terminal.app` has also changed significantly over the last couple of years.  Also, iTerm2 does seem to handle this better.  (I'm not 100% in love with iTerm2, it's a big sloppy drooling app, but it is at least different.)

**Comment by cgull** [comment] 2017-03-27 16:41
@Ghosthree3, could you try mosh-1.3.0 and see if it resolves your problem?

**Comment by johnhawkinson** [comment] 2017-03-27 18:38
> @johnhawkinson, it might not be (only) a change in Mutt causing you grief, `Terminal.app` has also changed significantly over the last couple of years.

Indeed. So, trying plain old `xterm` (as part of `XQuartz` 2.7.11):

`xterm` + `ssh` + `mutt` works fine without space-padding.
`xterm` + `ssh`  + `screen` + `mutt` pads spaces.

And then `mosh` behaves the same way:

`xterm` + `mosh` + `mutt` works fine without space-padding.
`xterm` + `mosh`  + `screen` + `mutt` pads spaces.

pointing the finger at `screen` (and `Terminal.app`). 
blaaaaaaaaaaaah.

**Comment by johnhawkinson** [comment] 2017-03-28 05:08
The more I think about this, the more I wonder if a Great Big Hammer of "unconditionally strip trailing whitespace" would be a helpful option. Such a thing vaguely (vaguely) reminds me of `screen`'s `J` copy option:

```
         J joins lines. It toggles between 4 modes: lines  separated  by  a  newline
           character (012), lines glued seamless, lines separated by a single white-
           space and comma separated lines. Note that you can  prepend  the  newline
           character with a carriage return character, by issuing a "crlf on".
```

I imagine mosh maintainers would find it too hackish?

**Comment by Ghosthree3** [comment] 2017-03-28 12:31
@cgull I wasn't able to reproduce it under the conditions I was getting it in before. If that changes I'll let you know but it _seems_ fixed. Nice work!

**Comment by cgull** [comment] 2017-03-31 04:45
@johnhawkinson, I spent a little time trying your test case of screen + mutt, with both ssh and Mosh and iTerm2 3.1.20170327-nightly and OS X 10.12.4 Terminal.app.  When I switch from Terminal.app to iTerm2, that eliminates the end of line padding but not joined lines.  I don't get any substantial difference between Mosh and ssh for either of the terminal emulators.

I don't think Mosh is the right place to try and clean up this problem (especially since the redisplay code that handles this is pretty complex).  Better would be the outer terminal emulator, or the app producing non-copy-paste-friendly output.

**Closed** 2017-03-31 04:48 UTC
Labels: Terminal emulation
