### ISSUE TITLE
Per-server configure via ~/.moshrc ?

### ISSUE THREAD

**Issue by galaxy001** [mobile-shell/mosh#926] opened 2017-09-14 11:48 UTC
I have several servers with different firewall settings. So I need to set `--port` for different host.
And an old Mac server require to set `--server=/usr/local/bin/mosh-server` to connect.

Would you add a client-side configure file like `~/.moshrc` to store those options for those ssh hosts in  `~/.ssh/config` ?

e.g.
In `~/.ssh/config`:
````ini
Host	Test1
  User galaxy
  Port 5678
  HostName some.where.org
````

In `~/.moshrc`:
````ini
Host	Test1
  Port 6666:7777
  server /usr/local/bin/mosh-server
Host	192.168.22.33
  Port 8888:8899
  server /usr/bin/mosh-server
````

I just came to #431, 4 years before and still opened, ...

**Comment by eminence** [comment] 2017-09-14 13:30
I'm going to close this as a duplicate of #431, in order to help reduce clutter on the issue tracker.

**Closed by eminence** 2017-09-14 13:30 UTC
