### ISSUE TITLE
Introduce configuration file

### ISSUE THREAD

**Issue by tyalie** [mobile-shell/mosh#1314] opened 2024-03-17 05:15 UTC
Hi I noticed during usage and especially exposing multiple mosh servers behind an IPv4 NAT, that it is nearly impossible to configure the port range that will be chosen without client configuration. Especially the way `mosh-server` expects its arguments (with `mosh-server new -p ...`), prevents one from writing a small wrapper script that would handle that.

As a solution I would suggest a very simple configuration file that can be parsed, allowing system administrators to configure utilized port range without a user requiring to understand the limitations of the endpoint.

**Comment by achernya** [comment] 2024-03-17 05:43
Duplicate of #431

**Closed by achernya** 2024-03-17 05:43 UTC

**Comment by tyalie** [comment] 2024-03-17 15:28
But what I'm proposing here is the other way around. That would be a configuration file on the host, instead of the client.
