### ISSUE TITLE
Rendering of "…" (0x2026) moves cursor to the wrong place on Solaris and AIX

### ISSUE THREAD

**Issue by glance-** [mobile-shell/mosh#361] opened 2012-12-20 16:19 UTC
``` bash
$ perl -e 'binmode STDOUT, ":utf8"; print chr(0x2026) for 1..10;'
…………………………$ a         a
```

What i did was run that perl-line to print some unicode dots, then type a "a" <backspace> and then a "a" again. Instead of erasing the first "a", it moved the cursor to the wrong place in my term.

I haven't managed to isolate where the width calculations goes wrong.

I have noticed this issue only when i mosh to a Solaris or AIX machine. When i mosh to a Linux- or Mac OS X-machine, everything works as expected.

 I plan to work some on this issue and try to figure out where the character with calculations fails.

If anyone can help with some smaller test cases i'm happy to give them a spin.

**Comment by mikaabra** [comment] 2017-09-05 06:32
I am having this problem as well. 

In QP encoding, my problematic character string looks like this:

Subject: =?UTF-8?Q?=F0=9F=9A=9A_ORDER_SHIPPED:

It's rendered as a multicolor vehicle (truck) preceding "ORDER SHIPPED".

This is on fully updated latest MacOS against a debian 9 machine, running alpine to deplay email. Regular ssh doesn't show the problem.

**Comment by achernya** [comment] 2023-01-20 00:10
I believe this is a duplicate of #234

**Closed by achernya** 2023-01-20 00:10 UTC
Labels: Solaris
