### ISSUE TITLE
Did not find remote IP address

### ISSUE THREAD

**Issue by cossio** [mobile-shell/mosh#1242] opened 2022-11-19 10:59 UTC
On a freshly installed mosh (via `brew install mosh`, on a Macbook with M2 chip):

```
(base) ➜  ~ mosh my_server_name 
/opt/homebrew/bin/mosh: could not get canonical name for my_server_name: nodename nor servname provided, or not known
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
/opt/homebrew/bin/mosh: Did not find remote IP address (is SSH ProxyCommand disabled?).
```

`ssh my_server_name` works wonderfully.

What's wrong here?

**Comment by eminence** [comment] 2022-11-22 22:58
Is `my_server_name` the actual name of your host, or is it an alias in `.ssh/config`?    Is this host special in any way?

**Comment by alanwilter** [comment] 2022-12-20 08:27
>  Could this make a difference?

Yes, see #970.

**Comment by achernya** [comment] 2023-02-24 05:47
Duplicate of #970

**Closed by achernya** 2023-02-24 05:47 UTC
Labels: support
