### ISSUE TITLE
[Support] mount Mosh (File System)

### ISSUE THREAD

**Issue by ghost** [mobile-shell/mosh#280] opened 2012-05-25 00:37 UTC
Hi,

Please Add support mount moshfs

**Comment by chadwickboggs** [comment] 2015-01-08 22:20
+1

**Comment by albertz** [comment] 2015-05-07 12:41
That cannot be that hard, can it? There are many available implementations for reliable streams. So, just nobody had time to do this, or are there more non-trivial problems which I'm not seeing right now?

**Comment by rnewton** [comment] 2015-05-18 13:56
+1

Though perhaps this would work best as a related project. sshfs isn't a part of ssh, it just uses it.

**Comment by oozie** [comment] 2015-08-06 21:27
+1

**Comment by kkszysiu** [comment] 2015-08-19 11:04
+1

**Comment by joscarras** [comment] 2015-10-01 13:11
+1

**Comment by jiyinyiyong** [comment] 2015-10-03 04:02
Anyone knows how is this project now? https://github.com/leonidg/moshfs

**Comment by timotheecour** [comment] 2016-08-25 16:16
+1

**Comment by liammac** [comment] 2017-01-18 17:30
+1

**Comment by bbruneau** [comment] 2017-02-26 20:57
+1

**Comment by Titousensei** [comment] 2017-03-13 20:43
+1

**Comment by j4hangir** [comment] 2017-05-22 21:29
+1

**Comment by Colossus** [comment] 2017-10-14 00:27
+1

**Comment by vladsaveliev** [comment] 2017-12-05 05:17
+1

**Comment by anhnhoktvn** [comment] 2018-03-26 01:44
+1

**Comment by j4hangir** [comment] 2018-11-09 12:42
+1

**Comment by tlhonmey** [comment] 2019-01-14 23:40
It occurs to me that a reliable byte stream is not necessary for transferring files or filesystem metadata, only reliable byte transfer.  Neither end has to care what order the bytes are received in, only that they make it.

File transfer client to server is easy since Mosh makes sure all bytes are transmitted in that direction.  All it needs is an escape sequence and/or (preferably and) initialization mode to tell the client and server programs to save a data stream instead of running it through the shell.

Mosh already has reliable transfer of the final state of its buffer, it just might skip some of the intermediate states.  Mosh already has the ability to resize its buffer when the terminal is resized.  For file transfer server to client, encode the file in a way that will not be mangled (Base64 should be perfectly safe worst-case) and then resize the client-side buffer sufficiently large to hold the encoded file.  Client then talks to server in the usual way until it is certain that its buffer is in-sync, at which point it decodes the file data and saves it and then resizes the buffer back to the necessary dimensions.  For large files optionally split them into chunks to avoid exhausting client-side memory.

Once bare file transfer capability is completed, layering a "moshfs" overtop of it should be relatively simple.

**Comment by him229** [comment] 2019-06-07 15:54
+1

**Comment by cgull** [comment] 2019-06-08 00:45
I want to point out that NFS over UDP with hard mounts is conceptually somewhat like Mosh's functionality with terminals, and it's already available in most OSes other than Windows.

For the record, Mosh is unlikely to add direct/native support for filesystems; it is after all primarily a virtual terminal.  If it ever does become able to do filesystems, it'll be by tunneling reliable byte streams, as discussed in issues #41, #120, #261.

**Comment by dm17** [comment] 2021-05-22 21:16
SSHFS still the best way to mount filesystem over the network (securely)? Any news on using mosh for this to keep it alive?
Thanks!

**Comment by ralyodio** [comment] 2021-09-28 09:18
I'm also wanting to use mosh to mount a filesystem remote (linux)

**Comment by achernya** [comment] 2023-01-19 23:37
It sounds like folks here really want "sshfs, but using QUIC". While we're excited about this idea, it's unclear that it belongs in mosh. There's nothing about the mosh protocol that makes it particularly well-suited for large file transfers, and QUIC has many of the same roaming capabilities mosh does.

**Closed by achernya** 2023-01-19 23:37 UTC
Labels: feature, Reliable byte stream

**Comment by dm17** [comment] 2023-01-20 06:22
Perhaps some filesystem mount over tailscale or wireguard is more ideal?

**Comment by j4hangir** [comment] 2023-01-20 15:38
The rationale behind this request was the simplicity and ubiquity of MOSH, I have terminal open all the time on different devices and never need to worry about a closed connection, hence the idea to keep a simple folder or whatever mounted as well.

I don't understand why it got closed. This could've been maybe not the most efficient, but definitely a simple elegant solution.

**Comment by eminence** [comment] 2023-01-20 15:53
> but definitely a simple elegant solution.

I believe you are drastically underestimating the work involved here, if you think that this is a simple thing to develop :)

**Comment by j4hangir** [comment] 2023-01-21 02:12
> > but definitely a simple elegant solution.
> 
> I believe you are drastically underestimating the work involved here, if you think that this is a simple thing to develop :)

Definitely not simple in implementation but simple in being a straightforward solution :) Something like this:

`mosh -mount user@host:/home/user/data /Volumes/`

For the implementation, from what I gather it's also not gotta be too complicated given that there should be applications out there that perform sync-over-ssh (rsync, etc.), if one could replace the SSH part with that of MOSH, then theoretically everything should work out of the box. This apparently brings us back to the #41(X11-Forwarding) issue.


Either way, these are just still ideas, overall it could've been a great addition to MOSH.

**Comment by tlhonmey** [comment] 2023-01-21 05:46
The problem is that things like filesystem mounts and X11 Forwarding require sending every bit of a stream, while MOSH is specifically designed to discard all but the most recent data in the interest of getting the latest screen state there as fast as possible.

You could do some of it by using the screen buffer as your metaphor instead of a stream of data.  Equivalent to transferring a file by breaking it into one-screen-sized chunks of encoded data and only asking for the next one once you've copied down the first one.  But, at the moment, MOSH only supports one buffer at a time so that would need to be addressed first.  It's quite a bit of work and not really the main point of using something like MOSH since things like a filesystem mount will hang big sections of your system waiting on latency whether you're using MOSH or just sshfs.

Automated single-file transfer could be handy though, even if it has to use the main buffer to do it.

**Comment by albertz** [comment] 2023-01-21 09:50
I think the only real feature people want here is that it seamlessly works when the user switches networks or when the connection is bad or so. This is for many people one of the killer feature of Mosh. Sshfs with reconnect is not really so seamless.

**Comment by j4hangir** [comment] 2023-01-21 21:45
> I think the only real feature people want here is that it seamlessly works when the user switches networks or when the connection is bad or so. This is for many people one of the killer feature of Mosh. Sshfs with reconnect is not really so seamless.
> 

That really sums it up, I personally wouldn't care about real-time performance or even resource hogging as much, as long as it could seamlessly sync a remote endpoint on my rig. May be MOSH isn't the best foundation, but I believe that really is the spirit behind the feature request.

**Comment by achernya** [comment] 2023-01-21 21:55
The mosh issue tracker is intended to be representative of feature requests or bugs in mosh. We'd rather not lead the community on by leaving this open and give the impression that the mosh contributors are going to work towards this.

As I said earlier, the idea is exciting. But we don't feel mosh is the appropriate place for it.
