### ISSUE TITLE
mosh/ssh crash on ubuntu 20.10 in malloc_* functions

### ISSUE THREAD

**Issue by docsmooth** [mobile-shell/mosh#1138] opened 2021-05-06 17:14 UTC
Similar to issue #1120  except that I cannot get mosh to work at all since upgrading to 20.10.
```
$ mosh 127.0.0.1
malloc_consolidate(): unaligned fastbin chunk detected
/usr/bin/mosh: Did not find mosh server startup message. (Have you installed mosh on your server?)
$ mosh `hostname`
The authenticity of host 'l-7k0s2z2 (<no hostip for proxy command>)' can't be established.
ECDSA key fingerprint is SHA256:mwLrYTD8PDq2LcECR6o1ysrPGUp6EmcriCOhaOafojk.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'l-7k0s2z2' (ECDSA) to the list of known hosts.
malloc_consolidate(): invalid chunk size
/usr/bin/mosh: Did not find mosh server startup message. (Have you installed mosh on your server?)
$ mosh `hostname -f`
Warning: Permanently added 'l-7k0s2z2.<redacted>' (ECDSA) to the list of known hosts.
malloc_consolidate(): unaligned fastbin chunk detected
/usr/bin/mosh: Did not find mosh server startup message. (Have you installed mosh on your server?)
$ mosh -4 rob@`hostname -f`
Warning: Permanently added '<redacted>' (ECDSA) to the list of known hosts.
malloc_consolidate(): unaligned fastbin chunk detected
/usr/bin/mosh: Did not find mosh server startup message. (Have you installed mosh on your server?)
$ mosh rob@`dig AAAA $( hostname -f ) @prwndcns01 +short | awk '{print; exit }'`
The authenticity of host '<redacted>:8573:54dd:b3ba:8aba (<no hostip for proxy command>)' can't be established.
ECDSA key fingerprint is SHA256:mwLrYTD8PDq2LcECR6o1ysrPGUp6EmcriCOhaOafojk.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '<redacted>:8573:54dd:b3ba:8aba' (ECDSA) to the list of known hosts.
malloc_consolidate(): invalid chunk size
/usr/bin/mosh: Did not find mosh server startup message. (Have you installed mosh on your server?)
```

same errors talking to my CentOS 6 and 7 boxes with mosh.  I'm not sure *which* attempt generated it, but I do have the Ubuntu crash report which appears to actually be in *ssh*

but I can ssh to myself no problem.

```
$ ssh localhost
Welcome to Ubuntu 20.10 (GNU/Linux 5.8.18.20201102 x86_64)

* Documentation:  https://help.ubuntu.com
* Management:     https://landscape.canonical.com
* Support:        https://ubuntu.com/advantage

0 updates can be installed immediately.
0 of these updates are security updates.

No mail.
Last login: Thu May  6 12:06:30 2021 from localhost
$
```
The top of the bugreport is:
```
ProblemType: Crash
Architecture: amd64
CrashCounter: 1
CurrentDesktop: KDE
Date: Thu May  6 12:01:38 2021
DistroRelease: Ubuntu 20.10
ExecutablePath: /usr/bin/ssh
ExecutableTimestamp: 1615299437
ProcCmdline: ssh -n -tt -S none -o ProxyCommand='/usr/bin/mosh'\ '--family=prefer-inet'\ --fake-proxy\ --\ %h\ %p l-7k0s2z2 -- mosh-server\ 'new'\ '-c'\ '256'\ '-s'\ '-l'\ 'LANG=en_US.UTF-8'\ '-l'\ 'LANGUAGE=en_US'\ '-l'\ 'LC_NUMERIC=en
_US.UTF-8'\ '-l'\ 'LC_TIME=en_US.UTF-8'\ '-l'\ 'LC_COLLATE=en_US.UTF-8'\ '-l'\ 'LC_MONETARY=en_US.UTF-8'\ '-l'\ 'LC_MEASUREMENT=en_US.UTF-8'
ProcCwd: /home/rob
ProcEnviron:
 SHELL=/bin/sh
 LANGUAGE=en_US
 LC_MONETARY=en_US.UTF-8
 LANG=en_US.UTF-8
 TERM=xterm-256color
 LC_MEASUREMENT=en_US.UTF-8
 XDG_RUNTIME_DIR=<set>
 LC_TIME=en_US.UTF-8
 LC_COLLATE=en_US.UTF-8
 PATH=(custom, user)
 LC_NUMERIC=en_US.UTF-8
ProcMaps:
 56366e8bb000-56366e8c5000 r--p 00000000 fd:01 39328923                   /usr/bin/ssh
 56366e8c5000-56366e938000 r-xp 0000a000 fd:01 39328923                   /usr/bin/ssh
 56366e938000-56366e97b000 r--p 0007d000 fd:01 39328923                   /usr/bin/ssh
 56366e97c000-56366e97f000 r--p 000c0000 fd:01 39328923                   /usr/bin/ssh
 56366e97f000-56366e980000 rw-p 000c3000 fd:01 39328923                   /usr/bin/ssh
 56366e980000-56366e984000 rw-p 00000000 00:00 0
 56366f81f000-56366f897000 rw-p 00000000 00:00 0                          [heap]
```

**Comment by docsmooth** [comment] 2021-05-06 19:42
followup: I can run mosh-server inbound TO the Ubuntu 20.04 box, it's just the outbound connections that are failing.

**Comment by andersk** [comment] 2021-05-06 20:45
As you noted, the crash is in `ssh`. Can you try these `ssh` commands to narrow down where?

1. `ssh -n -tt -S none -o ProxyCommand='/usr/bin/mosh --family=prefer-inet --fake-proxy -- %h %p' l-7k0s2z2 -- 'echo hello'`
2. `ssh -n -tt -S none l-7k0s2z2 -- 'echo hello'`
3. `ssh -n -tt l-7k0s2z2 -- 'echo hello'`
4. `ssh -n -tt l-7k0s2z2 -- 'echo hello'`
5. `ssh -n l-7k0s2z2 -- 'echo hello'`
6. `ssh l-7k0s2z2 -- 'echo hello'`

**Comment by docsmooth** [comment] 2021-05-06 21:23
```
16:20 rob@l-7k0s2z2:~$ ssh -n -tt -S none -o ProxyCommand='/usr/bin/mosh --family=prefer-inet --fake-proxy -- %h %p' l-7k0s2z2 -- 'echo hello'
MOSH IP 127.0.1.1
malloc_consolidate(): invalid chunk size
                                        Aborted (core dumped)
16:20 rob@l-7k0s2z2:~$ ssh -n -tt -S none l-7k0s2z2 -- 'echo hello'
hello
Connection to l-7k0s2z2 closed.
16:20 rob@l-7k0s2z2:~$ ssh -n -tt l-7k0s2z2 -- 'echo hello'
hello
Connection to l-7k0s2z2 closed.
16:20 rob@l-7k0s2z2:~$ ssh -n -tt l-7k0s2z2 -- 'echo hello'
hello
Connection to l-7k0s2z2 closed.
16:21 rob@l-7k0s2z2:~$ ssh -n l-7k0s2z2 -- 'echo hello'
hello
16:21 rob@l-7k0s2z2:~$ ssh l-7k0s2z2 -- 'echo hello'
hello
```

**Comment by andersk** [comment] 2021-05-06 21:54
Hmm, something to do with the `ProxyCommand`. What if you try a different `ProxyCommand`?

`ssh -n -tt -S none -o ProxyCommand='nc %h %p' l-7k0s2z2 -- 'echo hello'`

**Comment by docsmooth** [comment] 2021-05-07 03:14
@andersk thank you - that was the piece I needed to hunt this down.  It's a bug in OpenSSH: https://www.mail-archive.com/openssh-bugs@mindrot.org/msg14937.html

```
22:02 rob@l-7k0s2z2:~$ /usr/bin/ssh -n -tt -S none -o ProxyCommand='nc %h %p' l-7k0s2z2
malloc_consolidate(): invalid chunk size
                                        Aborted (core dumped)
22:04 rob@l-7k0s2z2:~$ /usr/bin/ssh -n -tt -S none -o GSSAPITrustDns=no -o ProxyCommand='nc %h %p' l-7k0s2z2
Welcome to Ubuntu 20.10 (GNU/Linux 5.8.18.20201102 x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

7 updates can be installed immediately.
4 of these updates are security updates.
To see these additional updates run: apt list --upgradable

No mail.
Last login: Thu May  6 16:20:48 2021 from 127.0.0.1
```
So disabling GSSAPITrustDNS fixes it:

```
22:10 rob@l-7k0s2z2:~$ mosh -ssh "ssh -o GSSAPITrustDNS=no" localhost
22:11 rob@l-7k0s2z2:~$ ps -elf |grep $$
0 S rob       532352  532351  0  80   0 -  9535 do_wai 22:11 pts/13   00:00:00 -bash
4 R rob       532417  532352  0  80   0 -  9704 -      22:11 pts/13   00:00:00 ps -elf
0 S rob       532418  532352  0  80   0 -  2254 pipe_r 22:11 pts/13   00:00:00 grep 532352
22:11 rob@l-7k0s2z2:~$ ps -elf |grep 532351
1 S rob       532351       1  0  80   0 -  5716 poll_s 22:11 ?        00:00:00 mosh-server new -c 8 -s -l LANG=en_US.UTF-8 -l LANGUAGE=en_US -l LC_NUMERIC=en_US.UTF-8 -l LC_TIME=en_US.UTF-8 -l LC_COLLATE=en_US.UTF-8 -l LC_MONETARY=en_US.UTF-8 -l LC_MEASUREMENT=en_US.UTF-8
0 S rob       532352  532351  0  80   0 -  9535 do_wai 22:11 pts/13   00:00:00 -bash
0 S rob       532498  532352  0  80   0 -  2254 pipe_r 22:12 pts/13   00:00:00 grep 532351
22:11 rob@l-7k0s2z2:~$ exit
[mosh is exiting.]
22:14 rob@l-7k0s2z2:~$ /usr/bin/ssh -V
OpenSSH_8.3p1 Ubuntu-1ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020
```
So... wait on SSH to fix that bug.

**Comment by eminence** [comment] 2021-05-07 03:26
Nice work.  Since it looks like you tracked down the root cause to openssh (and documented a workaround for any future visitors to this issue), I'm going to close this issue if that's OK with you.

**Closed by eminence** 2021-05-07 03:26 UTC

**Comment by docsmooth** [comment] 2021-05-07 03:52
For future reference, here's the but (private as of this posting) on Ubuntu, raised against both mosh and openssh packages: https://bugs.launchpad.net/ubuntu/+source/mosh/+bug/1927671  Confirming 100% OK to close. since this was my first issue with this project, I wasn't sure if I should have just closed it myself when I discovered RCA and workaround.
