### ISSUE TITLE
custom port number and user@host  vnc tunnel

### ISSUE THREAD

**Issue by blub4747** [mobile-shell/mosh#1022] opened 2019-01-21 10:24 UTC
Hi guys,

I want to know if its possible to add a vnc portforwarding tunnel to add typical 
`ssh -p 2200 -L5901:localhost:5901 user@remotehost -Nf`
to the following line
https://unix.stackexchange.com/questions/208465/problem-accessing-server-with-vnc
` mosh --ssh="ssh -p 2222" user@host`

thank you,blub4747

**Comment by andersk** [comment] 2019-01-21 13:05
No, Mosh does not support port forwarding at this time. Closing as a duplicate of #337.

**Closed by andersk** 2019-01-21 13:05 UTC
