### ISSUE TITLE
Systemd-logind "KillUserProcesses=yes" causing mosh failure

### ISSUE THREAD

**Issue by krathalan** [mobile-shell/mosh#1171] opened 2022-01-31 22:14 UTC
I have been troubleshooting this issue I was having with mosh for the last two hours and I thought it might be helpful to add this to a "troubleshooting" section, either in the readme or on the mosh website.

The following snippet in a conf file under `/etc/systemd/logind.conf.d/` was causing the issue:
```
[Login]
KillUserProcesses=yes
```

Mosh was reporting the error `Nothing received from server on UDP port ....` and it wasn't clear what was causing the issue, as it does not resolve itself even when the firewall is disabled. I also tried manually using `mosh-server` and `mosh-client`, and I could get a mosh session to work, as well as a plain `ssh` session to work, but simply using `mosh` on the client machine wouldn't work.

I guess the issue is that mosh uses an ssh session to start `mosh-server` on the server machine, but that `mosh-server` process is immediately closed when mosh tries to switch from ssh to mosh when `KillUserProcesses=yes` is set. 

Removing `KillUserProcesses=yes` fixed my issue, and I hope this helps someone else.

**Comment by achernya** [comment] 2023-01-24 01:42
I think this is ultimately caused by the same underlying issue as #529. Marking as a duplicate of that.

**Closed by achernya** 2023-01-24 01:42 UTC
