### ISSUE TITLE
Is it possible to support Visual Studio Code remote development?

### ISSUE THREAD

**Issue by Celthi** [mobile-shell/mosh#1111] opened 2020-08-27 20:01 UTC
I saw people ask if Visual Studio Code could support Mosh as remote development in https://github.com/microsoft/vscode-remote-release/issues/334
But they reply that 

> vscode remote ssh requires ssh port forwarding to access the agent. AFAIK mosh doesn't provide such a feature.

Is that meaning Mosh need to support ssh port forwarding to let Visual Studio Code support Mosh?

**Comment by eminence** [comment] 2020-08-27 21:00
Hi, you're correct that it is not possible to use mosh for this, as mosh has no reliable byte stream.  

I'm going to close this as a duplicate of #337.   

To be honest, I expect that if Microsoft finds that their users are working in environments that can't sustain reliable TCP connections, they would deploy their own solution that's more tailored to their messaging system.  So I encourage any VSCode users to describe their requirement as "Need to support VSCode remote development with a poor/unreliable internet connection"  and not "Need to support mosh", since this gives the VSCode team a better set of requirements to work with.

**Closed by eminence** 2020-08-27 21:00 UTC

**Comment by Celthi** [comment] 2020-08-27 21:35
@eminence Thanks for the reply. I agree that the requirement for VSCode should be clearer than "need to..".
