### ISSUE TITLE
Mosh doesn't handle servers with multiple IPs gracefully

### ISSUE THREAD

**Issue by catharsis71** [mobile-shell/mosh#1293] opened 2023-09-04 17:36 UTC
1.  Use mosh to log in to a server via a DNS name that resolves to two IPs, each representing a different interface on the server

2.  Shut down one of the interfaces on the server

3.  If the shutdown interface was the one Mosh was using, the session will freeze indefinitely until the interface is unshut

4.  Mosh will apparently never even attempt to switch over to the other IP

In contrast, Eternal Terminal will only freeze up for a few seconds before switching to the other IP and recovering.

Even SSH handles this better than Mosh; an established SSH session won't switch to the other server IP but you can at least start an additional new SSH session and it'll work fine.

can Mosh's behavior in this regard be improved?

**Comment by achernya** [comment] 2023-09-04 18:40
This is effectively a duplicate of #855 -- I don't think anything additional is needed here.

**Closed by achernya** 2023-09-04 18:40 UTC
