### ISSUE TITLE
bash_completion explodes on parsing options

### ISSUE THREAD

**Issue by andersk** [mobile-shell/mosh#294] opened 2012-07-11 03:27 UTC
The bash_completion script explodes when parsing options that begin with `-`, such as `mosh --server=/<tab>`:

```
anders@fixed-disk:~$ mosh --server=/bash: illegal option -- -
bash: illegal option -- s
bash: illegal option -- e
bash: illegal option -- r
bash: illegal option -- v
bash: illegal option -- e
bash: illegal option -- r
bash: illegal option -- =
bash: illegal option -- /
error: _known_hosts_real: missing mandatory argument CWORD
```

**Comment by achernya** [comment] 2023-01-19 23:41
Closing since it seems this has not been reproduced since 2012.

**Closed by achernya** 2023-01-19 23:41 UTC
Labels: bug, good first issue
