### ISSUE TITLE
mosh does not take care from some options in ~/.ssh/config file

### ISSUE THREAD

**Issue by tootai** [mobile-shell/mosh#978] opened 2018-06-09 16:16 UTC
Hi,

we connect to customers servers using an ssh server, customers servers running autossh@reboot

At tech side we have in .ssh/config 

Host myHost ; doesn't need to have a DNS entry
    User myUser
    Port 12345
    ProxyCommand ssh ourssh.central.server.TLD nc localhost 54321 ;this being the port where autossh connect to  

With this set up, a simple ssh myHost does connect to the customer server. We would expect that mosh does the same but no, we receive:

/usr/bin/mosh: Could not connect to myHost: Aucune adresse associée avec le nom de l'hôte
ssh_exchange_identification: Connection closed by remote host
/usr/bin/mosh: Did not find remote IP address (is SSH ProxyCommand disabled?).

where Aucune adresse associée avec le nom de l'hôte means no address related to the hostname.

Would be a nice feature if mosh would have the same behavior as ssh.

Daniel

**Comment by andersk** [comment] 2018-06-09 18:49
Duplicate of #285. You may be able to use the new `--experimental-remote-ip` option described there, although keep in mind that Mosh traffic cannot be proxied at this time—this only affects the short-lived SSH connection that `mosh` makes at startup to launch `mosh-server`.

**Closed by andersk** 2018-06-09 18:49 UTC
