### ISSUE TITLE
Poor in-flight performance

### ISSUE THREAD

**Issue by gchallen** [mobile-shell/mosh#701] opened 2015-12-20 21:50 UTC
I just started using mosh and was expecting it to be a great fit for in-flight terminal use. However, I'm airborne now and the performance is poor. Here's what I've noticed:

* Predictive typing seems disabled almost all of the time.
* I repeatedly see the banner message regarding "Last contact..." (frequently) or (more rarely) "Last reply..." While that is happening the entire terminal seems locked down.

Together these two problems pretty much render mosh unusable—`ssh` is actually more interactive :-(.

Without knowing much about how `mosh` works, I suspect that the problem has to do with some kind of strange UDP packet filtering or selective dropping that JetBlue is doing on their FlyWi service. If someone can give me some guidance about the diagnostic output that would be helpful I'd be happy to debug this again in a few weeks on my flight home.

**Comment by cgull** [comment] 2015-12-20 23:54
I'm on a United Airlines flight right now using *their* wi-fi, and
it's working about as well as I'd expect for 700ms latency.

If you're still on your flight, two debug things will be useful:

tcpdump capture of the mosh session.  Look for packets every 3
seconds from client and server when the terminal session.  When you
are typing, you should see the client sending a UDP packet for each
character typed, basically, and a reply from the server in about
RTT+20ms.

`mosh-client -v 2> /tmp/logfile` and `mosh-server -v 2> /tmp/logfile`
will get you logs of packet transmission and reception.

Do you know which inflight Internet provider your airplane uses?
(Quite possibly Gogoair, which is *not* what's on my aircraft.)

If you're getting better function with ssh than with mosh, that sounds
like you've got a connection with 3s+ latency but relatively low
loss.  In that situation mosh will start complaining and ssh will work
but very slowly.

As for the prediction, that works better in some apps than others.  If
your app updates something elsewhere on the screen with every
character (ie cursor position on a status bar), prediction can't cope
with that.  It only really works with apps that send text to the
terminal more or less as an echo of what you typed.

**Comment by cgull** [comment] 2015-12-21 00:09
Two more things:

If the tcpdump capture shows the client changing its source port
frequently, then something is probably killing off UDP sessions.
There's not much mosh can do to solve that.  Use a VPN to get around
that.

I'm not sure exactly what happens to prediction when the overlay
messages are displayed (the banners that you see).  It's possible that
prediction stops when the overlays are drawn.  I'll look at that a
bit.

**Comment by keithw** [comment] 2015-12-26 03:45
(Hi Geoff!) You might also try the `--predict=experimental` option, which abandons any attempt to avoid false positives and just echoes every keystroke.

**Comment by gchallen** [comment] 2016-01-08 16:40
Thanks @cgull and @keithw. I'm back on the same carrier (JetBlue) and just performed the debugging steps you suggested on their in-flight network (the free plan on FlyFi, although perhaps the paid plan is better).

The `mosh-server` output is [here](https://github.com/mobile-shell/mosh/files/82957/mosh.txt), but `mosh-client` doesn't seem to allow a verbose option. I also have a screencast if that helps but I'll upload it later.

I think that @cgull's suspicions about `mosh` changing ports frequently is spot on, based on my largely `mosh`-knowledge-free perusal of the logs. A VPN is probably the way to go, although I wonder if the port jumping could be made a bit less disruptive...

@keithw: the `experimental` option doesn't help much, since what is really ruining performance is the repeated banners and reattempts by `mosh` to connect.

Thanks for your help, and hope this helps in some way. Otherwise `mosh` is a very impressive tool. Kudos.

**Comment by cgull** [comment] 2016-01-08 18:53
Yeah, that log is pretty dire.  mosh-client is port-hopping every
10-20s, because communications on any given UDP session is blocked after
3-6 seconds or so.

One idea:  try running mosh-server on a port commonly used by
VPNs/IPSEC-- 1194, 1701, 500 come to mind.

regards,

  --jh

**Comment by cgull** [comment] 2016-01-08 19:04
Hmm.  Much like the RTT estimation already running in mosh, we could have some kind of time estimation related to "connection" failure, so that Mosh would adapt automatically to frequent failures like this.  I feel like that would be gaming a firewall in this case, though.  Mosh *does* expect its network to operate normally at least once in a while.

**Comment by cgull** [comment] 2016-01-13 05:43
Closing; this appears to be the work of a firewall, not any particular fault in Mosh itself.

**Comment by keithw** [comment] 2016-01-13 19:18
@gchallen I'm a bit confused. The banner message ("Last contact" meaning both directions are broken, or "Last reply" meaning the uplink is broken) is just an overlay; it does not lock down the terminal. You should be able to keep typing with no problem and see the keystrokes show up if predictions are on (or forced on with `--predict=experimental`), whether there's a banner being shown or not. At least, that's the intended behavior and I just checked that it works for me.

It looks like mosh-client is switching ports because the existing port has been shut off by the firewall/NAT after a few seconds. Even after switching its outgoing datagrams to a new port, mosh-client will continue to accept replies on the old port just in case. Switching ports (by itself) does not cause a performance impact, at least as far as I know. It's an **effect** of the old port getting shut off, not (hopefully) a cause of user-visible problems. (mosh-server will happily accept valid datagrams coming from any port; it's not like there's a handshaking penalty.)

I think the unfortunate summary here is that this particular firewall doesn't like long-lived UDP connections. Honestly the fix probably involves making mosh-client switch outgoing port numbers more often. (Or, using TCP... :frowning:)

**Comment by nicowilliams** [comment] 2016-01-13 21:07
Maybe mosh should make its source port hopping timer shorter once it's tripped twice in short succession and it has seen source port hopping work at all.  Then lengthen the timer again later.  Adaptive timouts, basically.

**Comment by cgull** [comment] 2016-01-13 21:15
@gchallen, do you still have the screencast?  Seeing that will help us understand what's going on with predictive typeahead.

**Comment by gchallen** [comment] 2016-02-16 15:58
Sorry... just saw this now. Yes, through the magic of Dropbox's undelete function I do have the screencast: https://youtu.be/oqIe1TyRSB4

**Closed** 2016-03-29 19:45 UTC

**Comment by cgull** [comment] 2016-03-30 01:04
I looked at that screencast at the time, maybe we confirmed on IRC but I forgot to follow up here:  I think the behavior seen there is pretty consistent with loss of connectivity as I think is happening here.
