### ISSUE TITLE
Send a mosh-server payload along with ssh connection

### ISSUE THREAD

**Issue by laurent-descrivan** [mobile-shell/mosh#536] opened 2014-07-15 20:25 UTC
I just discovered mosh and it looks very promising! But I did expect at first to have a real drop-in replacement of ssh (ie not having to install mosh-server).

Did you consider embedding statically linked mosh-servers for different architectures, and sending them with the first ssh connection? You could have a strategy to detect server os/architecture and sending correct binary this way.

I just imagine that being fully retro-compatible (by not having to change the default setup of most servers), this feature would allow mosh to be much more easily adopted.

Disclaimer : I am not a sysadmin veteran and I could easily miss an obvious problem with this suggestion. Also, sorry if it's a duplicate I missed.

**Comment by notorand-it** [comment] 2015-01-02 21:33
You can do it  with bash.

**Comment by elyscape** [comment] 2015-10-20 18:02
@notorand-it What do you mean?

**Comment by notorand-it** [comment] 2015-10-20 18:43
@elyscape Bash (https://www.gnu.org/software/bash/) has the ability to handle UDP and TCP packets. In "theory"(tm) you could bootstrap a minimal mosh-like server written in bash in the case you don't have mosh installed in the remote server. Maybe you can also try a number of interpreters on the remote machine. Sending a binary poses constraints on the remote machine (32- vs 64-bit, Intel vs ARM etc.).

**Comment by haarp** [comment] 2015-11-28 11:16
A python or bash-based mosh server would seem like the most logical approach. Most, if not all Unix machines will have these interpreters, regardless of machine architecture.

I am administering dozens of servers, some of which I don't have root on. Installing mosh on them is not an option. It would be best of the mosh client could streamline all of the necessary steps to run mosh-server on the remote end.

In fact, implemented properly, the need for mosh-server as a standalone package could be avoided entirely.

**Comment by cgull** [comment] 2015-11-28 18:59
mosh requires a level of crypto and network support that just can't be done in bash.

As currently coded, mosh has inner loops that do comparison/rendering from complex data structures for the frame buffers for every update.  Doing it in Python is certainly possible, but I think it would be too slow to be usable-- the current Mosh design doesn't work well for interpreted languages.

But if anyone can prove me wrong, please do!

**Comment by andersk** [comment] 2017-06-02 00:55
Closing as duplicate of #188.

**Closed by andersk** 2017-06-02 00:55 UTC
