### ISSUE TITLE
firewall and forwarded port

### ISSUE THREAD

**Issue by kanor** [mobile-shell/mosh#383] opened 2013-01-24 14:09 UTC
[This might look similar to other issues but I its not]

So I have an open port on my firewall 12345 for both TCP and UDP and it forwards that traffic to my ssh servers port 22.
(firewall) 12345/TCP -> (machine) 22/TCP
(firewall) 12345/UDP -> (machine) 22/UDP

problem is mosh launches the mosh-server that it will listen on 12345/UDP instead of 22/UDP
could this be configured somehow?
thanks! and mosh is awesome!

**Comment by achernya** [comment] 2023-01-20 00:19
Marking as a duplicate of #365

**Closed by achernya** 2023-01-20 00:19 UTC
