### ISSUE TITLE
Combining character not appearing over mosh (but it does over ssh)

### ISSUE THREAD

**Issue by mml** [mobile-shell/mosh#1301] opened 2023-11-27 17:48 UTC
Going from Macbook Air (Sonoma 14.1) running 1.4.0
to amd64 workstation (Debian 12 Bookworm) running 1.4.0

Terminal emulator is iTerm2 3.4.21

Over ssh...
<img width="1419" alt="image" src="https://github.com/mobile-shell/mosh/assets/3115/b62030c8-8a4c-463e-9c4b-f0cf88279adc">

Over mosh...
<img width="1431" alt="image" src="https://github.com/mobile-shell/mosh/assets/3115/f0271403-8e84-40d5-bcfe-e1de2f685980">

The character in this example is U+20F0 COMBINING ASTERISK ABOVE if that makes a difference.

Cut-and-paste friendly repro: `perl -le 'binmode STDOUT, ":utf8"; print "({Kleene star} \x{20f0})"'`

**Comment by achernya** [comment] 2023-11-27 18:06
What is the value of $TERM in both cases? My suspicion is this is wcwidth not knowing this character under mosh.

**Comment by mml** [comment] 2023-11-27 18:33
> What is the value of $TERM in both cases? My suspicion is this is wcwidth not knowing this character under mosh.

It's `xterm-256color` in all cases (including on the local Mac).

**Comment by achernya** [comment] 2023-11-27 18:43
Yeah it's probably wcwidth then. Probably a duplicate of #1001 and friends.

**Closed by achernya** 2023-11-27 18:43 UTC
