### ISSUE TITLE
No commit for a long time. Is the project dead?

### ISSUE THREAD

**Issue by yingbo** [mobile-shell/mosh#1021] opened 2019-01-16 02:57 UTC
Is there any roadmap?

**Comment by vvug** [comment] 2019-01-18 18:45
At this point I hope somebody will fork it. Not only nothing new has been committed in months (despite the open issues and PRs, mosh is far from being "finished"), but no release has been tagged since July 2017, 76 commits ago, with new features and bug fixes that never saw the light in a new release!

The Debian freeze began a few days ago, so now the opportunity to have features like truecolor support in the next Debian stable (and derived distributions) is LOST.

**Comment by vvug** [comment] 2019-01-18 18:46
ping @cgull

**Comment by andersk** [comment] 2019-02-10 23:58
Closing as duplicate of #974. (And, while I don’t doubt that there are reasons to make a release, this report doesn’t give one, so it doesn’t really help anyone.)

**Closed by andersk** 2019-02-10 23:58 UTC
