### ISSUE TITLE
Keystroke oddness in htop & screen

### ISSUE THREAD

**Issue by Synchro** [mobile-shell/mosh#290] opened 2012-06-22 11:29 UTC
I often run htop inside screen (server on ubuntu lucid), but when I do so via mosh, most of the key commands (which do not require modifiers, just plain keys) do not work. Pressing any key (alphanum or cursor) will result in the currently selected process getting its 'nice' value incremented!
Running it outside mosh (through the same screen session) works fine.

**Comment by cgull** [comment] 2017-08-23 07:22
I can't reproduce this either, so I'm closing it as old and unreproduceable.  The htop key to increase the nice value is `[`, which does suggest some possible problem with our function key conversion.

**Comment by Synchro** [comment] 2017-08-23 07:41
FWIW, I still see this on all the servers I administer. I'm now running mosh 1.3.2, iTerm2 3.0.2, tmux 2.5.

**Comment by Synchro** [comment] 2017-08-23 07:54
I just noticed that my original description isn't correct. Not all keys cause nice to increase - up/down/left/right work correctly, as do escape, return, the alphanumeric keys and some function keys (F6, F10). The main thing I notice that increases the nice value is pressing F5 to toggle tree mode.

**Comment by cgull** [comment] 2017-08-28 03:14
I can't reproduce this new symptom either, with iTerm 3.1.beta.7, tmux 2.3 or 2.5, and mosh-devel, on two different servers.  F5 toggles tree mode nicely for me.  Could you try and narrow down the conditions that cause this?

**Comment by achernya** [comment] 2023-01-19 23:39
Seems like this can't be reproduced since 2017. Please reopen if you are able to reproduce.

**Closed by achernya** 2023-01-19 23:39 UTC
Labels: bug
