### ISSUE TITLE
Can't get mosh to work with ProxyCommand and Corkscrew "could not get canonical name"

### ISSUE THREAD

**Issue by gartha1** [mobile-shell/mosh#955] opened 2018-02-03 04:15 UTC
I am running cygwin.

My server running ssh and mosh is 165.x.x.x

I can do   ssh root@165.x.x.x

I can do  mosh root@165.x.x.x

So I think both ssh and mosh are fine server side.

Those two lines above don't use ProxyCommand.

I have this in my ~/.ssh/config file

Host abc
User root
Hostname 165.x.x.x

Host abc2
User root
ProxyCommand corkscrew 192.168.1.94 808 165.x.x.x 22 

(192.168.1.94 is an HTTP/HTTPS proxy set up on my LAN with ccproxy).

I can do  $ssh abc

I can do $ssh abc2

I can do $mosh abc

But I can't do $mosh abc2

$ mosh abc2
/usr/bin/mosh: could not get canonical name for abc2: Name or service not known
ssh_exchange_identification: Connection closed by remote host
/usr/bin/mosh: Did not find remote IP address (is SSH ProxyCommand disabled?).

harvey@samsung350 ~/.ssh

Which is the same error i'd get if I did

$mosh sfsdfsd

So mosh is acting like it can't see the abc2 entry!  But ssh can see it.

I tried changing the order of abc and abc2 in the config file.

i.e. changing 

Host abc
User root
Hostname 165.227.238.144

Host abc2
User root
ProxyCommand corkscrew 192.168.1.94 808 165.227.238.144 22 #.corkscrew-auth

into

Host abc2
User root
ProxyCommand corkscrew 192.168.1.94 808 165.227.238.144 22 #.corkscrew-auth

Host abc
User root
Hostname 165.227.238.144

Still.. ssh sees both abc and abc2,

mosh sees abc but doesn't see abc2.

If I make the config file contain only the abc2 entry, i.e. the entry with ProxyCommand, then still ssh sees it, mosh doesn't.

What do you suggest?

Thanks

**Comment by andersk** [comment] 2018-02-03 04:55
Mosh requires a direct UDP connection to the target host. There is currently no way to use Mosh behind a proxy server.

If you have an unusual setup where you are able to make a direct UDP connection but you need to use a proxy server to make the initial SSH connection that Mosh uses at the beginning to launch its UDP server, then you may be able to use the `--experimental-remote-ip` option described at #285.

(Either way, closing as a duplicate of #285, which is still open.)

**Closed by andersk** 2018-02-03 04:55 UTC
