### ISSUE TITLE
Fails to build against OpenSSL 3.0 with -Werror

### ISSUE THREAD

**Issue by keithw** [mobile-shell/mosh#1174] opened 2022-02-17 08:20 UTC
The dpkg build is failing for this reason:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1005718

**Comment by cgull** [comment] 2022-05-12 05:42
Debian's complaints about Mosh have been getting more insistent ("marked for autoremoval" today), so I'll point out that I wrote code to use OpenSSL's OCB in #924, which would fix this.  I do remember @keithw having some concerns about using OpenSSL's implementation, though.  The code is solid, but I did it on FreeBSD and there might be some rough edges to file down while bringing it to Linux.

**Comment by achernya** [comment] 2022-05-31 01:41
We've merged the Debian NMU which fixes the FTBFS by lowering the -Werror check level to allow the use of the deprecated APIs. However, it's clear to me that we need to have a proper fix for this in mosh 1.4, because we should not be depending on deprecated APIs. #924 is a larger patch set than I want to merge for the new release. 

Looking at the patch series, it seems the bulk of the work is in 5098897132d03d0f009b928463e1cb0105b33365, which mostly seems to be wrapping the OpenSSL AES-OCB APIs to make them conform to the original ocb.cc API? I agree we need to improve the commit to not re-initialize the context on every datagram. However, my preference would be to not modify ocb.cc, but rather a higher-level mosh API to use the OpenSSL APIs directly.

**Comment by achernya** [comment] 2022-06-14 15:48
I installed a 32-bit bionic VM and was not able to reproduce the test failure with g++ and clang++. I also ran a valgrind on the encrypt-decrypt test with both compilers and got no memory errors.

**Comment by achernya** [comment] 2022-06-14 16:46
More evidence it's assembly related:

```
achernya@bionic-i386:~/src/mosh$ OPENSSL_ia32cap=~0x200000000000000 src/tests/encrypt-decrypt 
achernya@bionic-i386:~/src/mosh$ OPENSSL_ia32cap=~0x200000000000000 src/tests/encrypt-decrypt && echo PASS || echo FAIL
PASS
achernya@bionic-i386:~/src/mosh$ src/tests/encrypt-decrypt && echo PASS || echo FAIL
Fatal assertion failure in function test_one_session at encrypt-decrypt.cc:122
Failed test: decrypted.text == plaintext
Aborted
FAIL
```

(The `OPENSSL_ia32cap=~0x200000000000000` zeroes out bit 57, the AES-NI bit)

**Comment by keithw** [comment] 2022-06-14 20:14
(FWIW, here is an arm64 Launchpad build that also failed: https://launchpadlibrarian.net/606999517/buildlog_ubuntu-xenial-amd64.mosh_1.3.2+1384-0ppa~ubuntu16.04.1_BUILDING.txt.gz)

**Comment by achernya** [comment] 2022-06-14 20:21
Nothing exciting there, Ubuntu 16.04's openssl is too old:

```
ocb_openssl.cc:47:32: error: ‘EVP_CTRL_AEAD_SET_IVLEN’ was not declared in this scope
   if (EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_AEAD_SET_IVLEN,
```

@bbarenblat is working on a patch that will work with older OpenSSL.

**Comment by achernya** [comment] 2022-06-14 22:26
I've been debugging this for a bit, and I've concluded there's definitely a bug in `aesni_ocb_encrypt` for x86. I added a memset to `Session::encrypt` to clear the AlignedBuffer, and wrote a deterministic test to try out with. It's suddenly very obvious what the problem is:

```
./encrypt-decrypt  -v
Deterministic session
ct         a68fbd5fabbd167005d78ab6e8302f5acefb33144d4ffa9587a60f3970ae850120b4636d2d2fc5316a2d9554de112e2457e3088f53cd5e8eefb5681ed84bb8f4fa64c220292c4a2dce332c1d99d73a948a079606bc9fb2c873d0c3376269c1cdc496b29b0d6f26a1f4354fd553008bd2bf85e3d40654bd9139d802ae36f2f2972f960ca9d472e43cd947f15b37665c8a9fd6512d058fae294c13de52831582d44d0f98fe6d299bfe3c9e8b918cba624b3097d58736319cc1000000000000000000000000000000000f7aa096e526747ed2624575cf688364c87975
Fatal assertion failure in function deterministic_session at encrypt-decrypt.cc:167
Failed test: ciphertext == target_ciphertext
Aborted
```
vs
```
$ OPENSSL_ia32cap=~0x200000000000000  ./encrypt-decrypt -v
Deterministic session
ct         a68fbd5fabbd167005d78ab6e8302f5acefb33144d4ffa9587a60f3970ae850120b4636d2d2fc5316a2d9554de112e2457e3088f53cd5e8eefb5681ed84bb8f4fa64c220292c4a2dce332c1d99d73a948a079606bc9fb2c873d0c3376269c1cdc496b29b0d6f26a1f4354fd553008bd2bf85e3d40654bd9139d802ae36f2f2972f960ca9d472e43cd947f15b37665c8a9fd6512d058fae294c13de52831582d44d0f98fe6d299bfe3c9e8b918cba624b3097d58736319cc177516c28fc172a3a0ff30586b01e5a9453b304c2df0038cc4b384cdc0e77ea8d5fd0a3
dec nonce  a68fbd5fabbd1670
dec pt     bf206327afe1d5ed1417acc5b6ab387ab8640668e7b8aacc956214422670d3ac3d2ee8ff6ad275439fc9214c413c7b4fc3cc0e4678415ca4394805f8a6df8ba0b58834444d2bb107ff9037a9ea9b821bd7211caf5f0e2565c7fef6014a584a7cb12e3516346df212e3b0cd7402e57eae5576b436f69a115e185f3d7872ca5ea458553910b1772312e4464eb85a2583dc10b1682e020ee090257394cb6a3262f71d427cad6cb679e4c325513fa71147a319bf09b7df2d574502d7656fc81062365a2340
```

A whole block of 16 bytes is just ... not encrypted. I haven't yet isolated which line of (perl)asm is responsible for this bug, but I did single-step it and observed that the 6-block path is run once, and then it falls-through to the 5-block path. So there's probably a fencepost error somewhere.

**Closed** 2022-06-28 01:10 UTC

**Comment by achernya** [comment] 2022-06-28 01:20
Although we implemented an OpenSSL-based OCB-AES mode directly in ocb_openssl.cc, with the latest changes @bbarenblat wrote, mosh will continue to use the ocb_internal.cc (formerly ocb.cc), but without using any now-deprecated OpenSSL APIs. the OpenSSL-based OCB-AES mode remains available for developer use, and at some future point when we gain confidence in it, it could be switched over as the default. That future is beyond the 1.4 release's horizon, however.
