### ISSUE TITLE
mosh fails with _clock_gettime error on OS X 10.11.6 and Xcode 8

### ISSUE THREAD

**Issue by yanokwa** [mobile-shell/mosh#807] opened 2016-09-26 11:04 UTC
mosh installed through the brew package manager runs, but when I try to connect to a server with an SSH key, it fails with "Symbol not found: _clock_gettime". The binary from https://mosh.org/#getting or building from source does not have this problem.

```
$ brew config

HOMEBREW_VERSION: 1.0.4-7-g6e57355
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 6e5735565b9a31ec2b01e02a479a361189729c22
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 109939afe4af2dd8742cbc31af1bc2b0e04a6556
Core tap last commit: 27 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/var/pyenv/shims/python => /usr/local/var/pyenv/versions/2.7.12/bin/python2.7
Ruby: /usr/local/var/rbenv/shims/ruby => /usr/local/var/rbenv/versions/2.3.1/bin/ruby
Java: 1.8.0_66, 1.7.0_45
macOS: 10.11.6-x86_64
Xcode: 8.0
CLT: 7.3.1.0.1.1461711523
X11: 2.7.9 => /opt/X11
```

```
$ mosh --version

mosh 1.2.6 [build mosh 1.2.6]
Copyright 2012 Keith Winstein <mosh-devel@mit.edu>
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

```
$ mosh --ssh="ssh -i /Users/user/.ssh/id_rsa" root@1.2.3.4

dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/Cellar/mobile-shell/1.2.6_2/bin/mosh-client
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/local/Cellar/mobile-shell/1.2.6_2/bin/mosh-client
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5
```

This was originally reported at https://github.com/Homebrew/homebrew-core/issues/5220 and patched at https://github.com/Homebrew/homebrew-core/pull/5247, but it's an upstream issue, so I'm reporting it here.

The fix in the brew formula was to set `ENV["ac_cv_search_clock_gettime"] = "no"`.

**Comment by noorul** [comment] 2016-09-26 11:13
I am facing this issue

**Comment by mistydemeo** [comment] 2016-09-27 00:34
To provide some context, this issue happens because Xcode 8 includes only the OS X 10.12 SDK. 10.12 introduced `clock_gettime`; the headers in the 10.12 SDK are properly guarded so that the definition is marked as unavailable when the deployment target is set to 10.11 or lower, but the weak symbol is still available in `libSystem`. The issue here happens because `AC_SEARCH_LIBS` checks the symbol by linking without encountering the availability declaration in the headers; a lot of projects are encountering similar bugs. https://github.com/Homebrew/homebrew-core/issues/2674 has some more details.

**Comment by cgull** [comment] 2016-09-29 05:51
There's something more to this.  I've built mosh with the Homebrew recipe prior to their fix, and `mosh --server=/usr/local/bin/mosh-server localhost` fails with the above error, but `mosh --local --server=/usr/local/bin/mosh-server 127.0.0.1` (a special mode for invoking mosh locally without going through ssh) works.  I suspect the login/session environment set up (or not) by sshd is involved here.

I've got a good `clock_gettime()` fix for configure.ac waiting, but I'd like to understand why this fails only some of the time, or some assurance that fixing that will resolve this.

**Comment by cgull** [comment] 2016-09-29 06:07
Actually, now I can't reproduce the error at all.  I need to look at this some more.

**Comment by DomT4** [comment] 2016-09-30 03:26
Homebrew is doing a bunch of env filtering for the 10.11 & Xcode 8 combination to try and prevent things like this popping up absolutely everywhere, so if you're trying to reproduce via `brew` we may be squashing the error in the background.

If you're trying to reproduce it via brew, using the older formula, try appending `--env=std` to your `brew install` command.

**Comment by cgull** [comment] 2016-10-01 04:59
I've now reproduced this with a native build on 10.11.6 + XCode 8.0 with old CLT from Xcode 7.x installed (or maybe no CLT installed, I'm a bit unclear on that point).  From what I understand this is unsupported/broken from Apple's point of view.  A trivial test program that uses `clock_gettime()` builds cleanly and fails to run as well.  So I'm inclined to describe this as "broken build environment".  The more careful autoconf checks I wrote (separating the library check from the function check) don't seem to avoid the problem either.

Running xcode-select prompted/installed a "new" CLT for me (still 7.3 actually), and after that Mosh builds properly.

If I'm reading correctly, Homebrew has added generic workarounds (including `-Werror=partial-availability`) to deal with this issue, as well as a specific change to the Mosh formula, so this should no longer be a problem there.

If somebody can show this failure happening with an Xcode/CLT configuration that Apple supports and represents as working, I'll add a workaround to the Mosh build.

**Comment by cgull** [comment] 2016-10-01 05:05
I just pushed b0facb55c48c1e84d1a855ea862d5381667effa3 which improves the configure tests for `clock_gettime()` but is **not** a workaround for the issues here.

**Comment by mistydemeo** [comment] 2016-10-02 22:45
> If somebody can show this failure happening with an OSX/Xcode/CLT configuration that Apple supports and represents as working, I'll add a workaround to the Mosh build.

The primary configuration where this occurs is Xcode 8 on OS X 10.11 *without* the CLT installed, which is a supported configuration... though one that has a lot of this kind of issue.

**Comment by nntoan** [comment] 2016-10-03 01:49
My solution is remove this Homebrew package and install from .pkg directly from the homepage.

**Comment by cgull** [comment] 2016-11-19 20:57
In the runup to release I'm looking at this again.  I no longer have a 10.11 system to test on, but I believe that multiple things make this no longer an issue:
* my commit b0facb5 (which does actually fix this, I think, contrary to my earlier statement)
* Homebrew build environment workarounds
* Xcode 8.1
Does anyone disagree?

**Comment by cgull** [comment] 2016-11-19 21:40
I ran a Travis build with OS X 10.11, XCode 8 and deployment target 10.11, and it seems to have properly discovered the lack of `clock_gettime()`:  https://travis-ci.org/cgull/mosh/jobs/177324748

**Comment by carloscabanero** [comment] 2016-12-22 22:35
I just run into this and made a few more discoveries. Long story short, Apple is doing some weird things with clock_gettime and unfortunately there is no reliable way to check whether it exists or not. We need a different way to force the configure on OSX to always use the HAVE_MACH_ABSOLUTE_TIME path.

And here is my experiment that explains why. I found this when recompiling / assembling a continuous integration server. I found that on iOS10 the clock_gettime was working, and on iOS9 it crashed with the same dylib error. Applying the patch from @cgull, if I set the IPHONE_DEPLOYMENT_TARGET to iOS9, the HAVE_MACH_ABSOLUTE_TIME will be compiled, if I set it to iOS10, clock_gettime will be compiled. iOS10 can run clock_gettime perfectly, but not iOS9-8, etc... I guess the same is happening with OSX/Xcode versions, some of them might support clock_gettime and then trigger that path, crashing on versions that do not.

As this is all dependent on the environment or target we compile with, if you are running it on the same one then you are fine (i.e. Homebrew). But in the case of binaries, we cannot be certain on where it will run. So I suggest forcing a path to always do HAVE_MACH_ABSOLUTE_TIME on Darwin based environments.

So yes, the patch works as long as you compile/run in the same environment, but unfortunately it cannot be used as a way to fix the general issue.

**Comment by andersk** [comment] 2016-12-22 23:37
@carloscabanero Apple documents the deployment target as “the earliest OS version on which your software can run”. It is not a bug that software targeted for iOS 10 crashes on iOS 9. Is there something more to your observation that I’m missing?

**Comment by cgull** [comment] 2016-12-24 03:39
Alright, that got complicated.  I *think* I understand most of what's going on now.  It's not just a build time issue, there is varying behavior at runtime too, at least for OS X.

The problem here is that OS X/iOS executables can be built to run on a range of OS versions with varying APIs, and you may have to detect what's available at runtime.  (This is separate from backward compatibility for executables built for older OS versions.  I think.)  The SDK version defines the latest API, and `MACOSX_DEPLOYMENT_TARGET`/`IOS_DEPLOYMENT_TARGET` defines the earliest API you want to support on your app.   So detecting a symbol at build time doesn't mean that it will be linked to anything at runtime, *if* `..._DEPLOYMENT_TARGET` specifies a lower version than the SDK version *and* the runtime OS is a lower version than the build time OS.  Since iOS is a cross-compilation target, that complicates things some more (I assume configure's test executables are being run on an iOS simulator-- but which iOS version?)

The simplest solution is to build with the SDK for the lowest OS version you want the app to run on, and set `..._DEPLOYMENT_TARGET` to that same version (or leave it unset, I'm not sure).  That's what I'm choosing to do for OS X.  This can get painful though, because newer versions of OS X and Xcode have limited-to-no compatibility with older SDKs.  (This is part of why I'm moving the OS X build to Travis.)  @carloscabanero, I don't know about iOS but i assume App Store baseline requirements are causing you pain in this area too.

The more complicated solution is to check for API availability at runtime.

https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/cross_development/Introduction/Introduction.html explains this all in detail.

For our purposes, `clock_gettime()` is an improvement on `mach_absolute_time()` (it doesn't sleep when the system does, and is more portable).  So I think adding runtime checks for `clock_gettime()` to the build-time checks for available clock sources is the best course here.  Pull request in a minute.

**Closed** 2017-03-26 19:59 UTC
