### ISSUE TITLE
Client not working on Bash on Windows

### ISSUE THREAD

**Issue by spkujis** [mobile-shell/mosh#781] opened 2016-07-29 06:53 UTC
When I try to use mosh as client with Bash on Windows, I get the following error:
Network exception: setsockopt: Invalid argument

I am not a developer and I know Bash on Windows is still in heavy development, but could this be something that can/needs be fixed in mosh?

Versions:
mosh 1.2.5 compiled from .tar.gz on this system (default repositories have 1.2.4a-1ubuntu1)
Windows 10 Insider Preview 14393

If you don't have access to Bash on Windows, I will gladly try to help, if you decide to look into this.

**Comment by Doridian** [comment] 2016-08-02 19:56
I am having a similar problem on Bash for Windows (or Linux Subsystem for Windows):

All I get on a successful connection is this:
```
user@PC:~$ mosh ansible@ansible


[mosh is exiting.]
```

**Comment by glensc** [comment] 2016-08-02 20:02
check if other tools like tmux work:
https://blogs.msdn.microsoft.com/commandline/2016/06/08/tmux-support-arrives-for-bash-on-ubuntu-on-windows/

as i read PTY support is not complete there, but probably there are updates on that....

**Comment by Doridian** [comment] 2016-08-02 20:05
tmux runs fine, screen just exits without an error like mosh

**Comment by cgull** [comment] 2016-08-02 21:47
I thought I answered this days ago, but I'm wrong.

Mosh *almost* works in Windows Subsystem for Linux.  Its pty support is now fine for Mosh.  At this point, only one thing is keeping Mosh from working-- a missing socket option for path MTU discovery causes Mosh to exit.  My position is that if Microsoft is offering Linux binary compatibility, this is their problem to fix.  However, the fix would be easy, and we have discussed changing how we do MTU discovery anyway.

I have a branch with the necessary changes (and some extras), https://github.com/cgull/mosh/tree/wsl-workarounds-14361.

**Comment by Doridian** [comment] 2016-08-02 23:28
@cgull Beautiful, I merged your branch with the latest of master (no significant changes, but if I build a nightly, might as well be latest) and now mosh works. Thanks :)

**Comment by cgull** [comment] 2016-08-03 05:30
I forgot to mention, I've reported this and it's in their queue: https://github.com/Microsoft/BashOnWindows/issues/170

**Comment by kaepora** [comment] 2016-08-17 10:38
I am also having this problem.

**Comment by cgull** [comment] 2016-09-18 03:27
Please upvote https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13413396-setsockopt-fd-ipproto-ip-ip-mtu-discover-fla to encourage Microsoft to do the right thing :)

**Comment by colemickens** [comment] 2016-09-29 01:11
I was just able to mosh into my server from WSL. I'm not sure if it's because of the new Insider build (14936) or because I upgrade the install to Xenial, but it seems to "just work" now. 👍

**Comment by colemickens** [comment] 2016-09-29 01:13
I am on build 14936 and I upgrade the install to Xenial.

`mosh` appears to just be working...

**Comment by colemickens** [comment] 2016-09-29 01:16
I apparently had built and patched it locally, so I take back my comment.

**Comment by cgull** [comment] 2016-10-13 05:52
The Microsoft people have heard your votes :)
https://github.com/Microsoft/BashOnWindows/issues/170#issuecomment-251247840

**Comment by deadalnix** [comment] 2017-01-03 10:27
While microsoft is getting its shit together, what are the workaround options ?

**Comment by cgull** [comment] 2017-01-05 06:31
Compiling the above-mentioned branch from source, or using Mosh under Cygwin or Msys2 are all usable workarounds.

**Comment by deadalnix** [comment] 2017-01-05 08:18
Thanks.

**Comment by metasoarous** [comment] 2017-01-13 21:09
For the record, there's also this issue: https://github.com/Microsoft/BashOnWindows/issues/1140

**Comment by cgull** [comment] 2017-03-26 20:21
Windows Insider build 15002 and later support Mosh probably, and in all likelihood that means it goes into the Windows Creator update as well.

**Closed by cgull** 2017-03-26 20:21 UTC

**Comment by deadalnix** [comment] 2017-03-28 21:35
I can confirm it is fixed using insider builds.

**Comment by huyinjie** [comment] 2017-03-29 13:30
@cgull  I am waiting Creator Update,hoping it won't Disappoint me.

**Comment by hossbeast** [comment] 2017-06-06 02:49
Just got the Windows Creator Update, and the first thing I did was boot up bash and try mosh.

Failure on the client with this error:
mosh: Nothing received from server on UDP port 60001.

Client
todd@hossbeast:~$ mosh --version
mosh 1.2.4a

Server (Ubuntu 16.04.1)
0 % mosh --version
mosh 1.2.5 [build mosh 1.2.5]

**Comment by hossbeast** [comment] 2017-06-06 03:03
I built from source and updated both sides to mosh-1.3.0, and continue to receive the same error.

**Comment by cgull** [comment] 2017-06-07 03:13
mosh works fine for me on the Windows Creator 1703 build.  The message you're getting is likely due to network connectivity issues, not issues with Windows itself.  Windows firewall/AV software can be difficult in this area.  Please try the troubleshooting tips in the FAQ at https://mosh.org.

**Comment by hossbeast** [comment] 2017-06-07 04:55
@cgull thanks, I assumed from my reading of this thread there was some Windows fix I needed, and jumped to conclusions. I fixed the firewall issue, and it now appears to be working.
