### ISSUE TITLE
mosh tries to select incorrect locale

### ISSUE THREAD

**Issue by thorgrin** [mobile-shell/mosh#1023] opened 2019-01-24 07:31 UTC
To fix problems with time formatting, I've changed my locale for time from eu_US.UTF-8 to `LC_TIME=en_GB.UTF-8`. However, after doing that, I cannot connect with mosh:

```
The locale requested by LC_CTYPE=en_US.UTF-8 isn't available here.
Running `locale-gen en_US.UTF-8' may be necessary.

The locale requested by LC_CTYPE=en_US.UTF-8 isn't available here.
Running `locale-gen en_US.UTF-8' may be necessary.

mosh-server needs a UTF-8 native locale to run.

Unfortunately, the local environment (LC_CTYPE=en_US.UTF-8) specifies
the character set "US-ASCII",

The client-supplied environment (LC_CTYPE=en_US.UTF-8) specifies
the character set "US-ASCII".

locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME=en_GB.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
Connection to vps.jezevec.eu closed.
/usr/bin/mosh: Did not find mosh server startup message. (Have you installed mosh on your server?)

```

I understand that the problem is missing `en_GB.UTF-8` locale on the other side, but the error messages seem incorrect - `en_US.UTF-8` is definitely available both on client and server. It should report missing `en_GB`, shouldn't it?

This is my mosh version, I'm running OpenSUSE Tumbleweed:
```
# mosh -v
mosh 1.3.2 [build mosh 1.3.2]
Copyright 2012 Keith Winstein <mosh-devel@mit.edu>
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by andersk** [comment] 2019-01-24 09:37
Duplicate of #1018.

**Closed by andersk** 2019-01-24 09:37 UTC
