### ISSUE TITLE
mosh and ProxyJump

### ISSUE THREAD

**Issue by alanwilter** [mobile-shell/mosh#1246] opened 2022-12-19 18:47 UTC
I have in my `.ssh/config` something like this:

```config
Host remote_server
  Hostname 123.456.111.111
  User joedoe
  IdentityFile ~/.ssh/id_rsa
  ProxyJump tails

Host tails
  Hostname tails.somewhere.com
  IdentityFile ~/.ssh/id_rsa
  User anotherjoe
```

Needless to say but `ssh remote_server` works fine, no password asked.

I'm using mosh 1.3.2 (remote server is Ubuntu 20.04 LTS, default mosh package).

On my mac I tried mosh 1.4 (homebrew) and mosh 1.3.2 (conda).

Using ssh debug cues the "best" I got so far was:

```bash
mosh --ssh="ssh -vv -W '[123.456.111.111]:22' tails" remote_server

OpenSSH_9.0p1, LibreSSL 3.3.6
debug1: Reading configuration data /Users/joedoe/.ssh/config
debug1: /Users/joedoe/.ssh/config line 6: Applying options for *
debug1: /Users/joedoe/.ssh/config line 28: Applying options for tails
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files
debug1: /etc/ssh/ssh_config line 54: Applying options for *
debug1: /etc/ssh/ssh_config line 58: Applying options for *
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug1: Executing proxy command: exec '/opt/homebrew/bin/mosh' '--family=prefer-inet' --fake-proxy -- tails.somewhere.com 22
debug1: identity file /Users/joedoe/.ssh/id_ed25519 type 3
debug1: identity file /Users/joedoe/.ssh/id_ed25519-cert type -1
debug1: identity file /Users/joedoe/.ssh/id_rsa type 0
debug1: identity file /Users/joedoe/.ssh/id_rsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_9.0
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.4
debug1: compat_banner: match: OpenSSH_7.4 pat OpenSSH_7.4* compat 0x04000006
debug2: fd 5 setting O_NONBLOCK
debug2: fd 4 setting O_NONBLOCK
debug1: Authenticating to tails.somewhere.com:22 as 'anotherjoe'
debug1: load_hostkeys: fopen /Users/joedoe/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: sntrup761x25519-sha512@openssh.com,curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-c
debug2: host key algorithms: rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
debug2: host key algorithms: ssh-rsa,rsa-sha2-512,rsa-sha2-256
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com
debug2: compression stoc: none,zlib@openssh.com
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: rsa-sha2-512
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ssh-rsa SHA256:l295MlPa6ATNX0jL+pxmIBFCWhhs6+gN1FzyJXUI3OY
debug1: load_hostkeys: fopen /Users/joedoe/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: Host 'tails.somewhere.com' is known and matches the RSA host key.
debug1: Found key in /Users/joedoe/.ssh/known_hosts:260
debug2: ssh_set_newkeys: mode 1
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug2: ssh_set_newkeys: mode 0
debug1: rekey in after 134217728 blocks
debug1: get_agent_identities: bound agent to hostkey
debug1: get_agent_identities: agent returned 3 keys
debug1: Will attempt key: /Users/joedoe/.ssh/id_rsa RSA SHA256:Hd2QpJYQKlvF2X0BRwic926WlXQKRWTePr7yvZHaDUg explicit agent
debug1: Will attempt key: /Users/joedoe/.ssh/id_ed25519 ED25519 SHA256:i0S6waRs7wnAwMW2z22SimiIqshAihg7iUxCfB2SlpM explicit agent
debug1: Will attempt key: /Users/joedoe/.ssh/id_rsa_baikal RSA SHA256:8iaoym6R7377jMWxzx7eEE1+m8xijyFGhqDyOFmHnsw agent
debug2: pubkey_prepare: done
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password,keyboard-interactive,hostbased
debug1: Next authentication method: publickey
debug1: Offering public key: /Users/joedoe/.ssh/id_rsa RSA SHA256:Hd2QpJYQKlvF2X0BRwic926WlXQKRWTePr7yvZHaDUg explicit agent
debug2: we sent a publickey packet, wait for reply
debug1: Server accepts key: /Users/joedoe/.ssh/id_rsa RSA SHA256:Hd2QpJYQKlvF2X0BRwic926WlXQKRWTePr7yvZHaDUg explicit agent
Authenticated to tails.somewhere.com (via proxy) using "publickey".
debug1: channel_connect_stdio_fwd: 123.456.111.111:22
debug1: channel 0: new [stdio-forward]
debug2: fd 3 setting O_NONBLOCK
debug2: fd 6 setting O_NONBLOCK
debug1: getpeername failed: Bad file descriptor
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: exec
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: client_input_hostkeys: searching /Users/joedoe/.ssh/known_hosts for tails.somewhere.com / (none)
debug1: client_input_hostkeys: searching /Users/joedoe/.ssh/known_hosts2 for tails.somewhere.com / (none)
debug1: client_input_hostkeys: hostkeys file /Users/joedoe/.ssh/known_hosts2 does not exist
debug1: client_input_hostkeys: no new or deprecated keys from server
debug2: channel_input_open_confirmation: channel 0: callback start
debug2: channel_input_open_confirmation: channel 0: callback done
debug2: channel 0: open confirm rwindow 2097152 rmax 32768
SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.3
# After a while:
debug2: channel 0: rcvd eof
debug2: channel 0: output open -> drain
debug2: channel 0: obuf empty
debug2: chan_shutdown_write: channel 0: (i0 o1 sock -1 wfd 6 efd -1 [closed])
debug2: channel 0: output drain -> closed
debug1: channel 0: FORCE input drain
debug2: channel 0: ibuf empty
debug2: channel 0: send eof
debug2: channel 0: input drain -> closed
debug2: channel 0: rcvd close
debug2: channel 0: almost dead
debug2: channel 0: gc: notify user
debug1: stdio forwarding: done
/opt/homebrew/bin/mosh: Did not find mosh server startup message. (Have you installed mosh on your server?)
```

Testing local (both mac and remote), works fine:

```bash
mosh --local 127.0.0.1

# Mac
ps uxw | grep mosh
joedoe 63130   0.0  0.0 409071888   8592 s006  S+    7:38pm   0:00.04 /opt/homebrew/Cellar/mosh/1.4.0/bin/mosh-client -# --local 127.0.0.1 | 127.0.0.1 60001
joedoe 63133   0.0  0.0 409063680   7328 s006  S+    7:38pm   0:00.00 mosh-server new -c 256 -i 127.0.0.1 -l LANG=en_GB.UTF-8

# Remote Ubuntu
joedoe  3184047  0.2  0.0  22608  8180 pts/16   S+   18:41   0:00 mosh-client -# --local 127.0.0.1 | 127.0.0.1 60001
joedoe  3184050  0.0  0.0  23036  5076 pts/16   S+   18:41   0:00 mosh-server new -c 256 -i 127.0.0.1 -l LANG=en_GB.UTF-8 -l LANGUAGE=en_GB:en
```

`joedoe` is the same user in both local and remote.

What am I missing?

**Comment by alanwilter** [comment] 2022-12-20 08:23
I see mine may be a duplication of #970

**Comment by achernya** [comment] 2023-01-24 01:29
I agree this is a duplicate of #970. Fundamentally mosh doesn't work with ProxyJump because we need a UDP forwarder, and a sufficiently robust one has not yet been written.

**Closed by achernya** 2023-01-24 01:29 UTC
