### ISSUE TITLE
High CPU Usage on FreeBSD 9/amd64

### ISSUE THREAD

**Issue by nvx** [mobile-shell/mosh#297] opened 2012-07-13 07:37 UTC
Installed via ports, mosh 1.1.3 exhibited low (under 1%) cpu usage of both the client and the server, however upon updating to mosh 1.2.2 cpu usage skyrocketed to a point where typing commands and viewing the output of say 'ls' was noticeably delayed, top reports cpu usage as 25% or so for both the client and server (on a core2 duo) and as high as 5% usage when idle.

This is most noticeable on lower-spec machines like Intel Atoms, but it was still quite noticeable on a Core2 Duo when you were looking for it.

Unfortunately I haven't tested any versions in-between 1.2.2 and 1.1.3 so I'm not sure where exactly it occurred. To compare, running "while true ; do ; ls ; done" in the same directory over ssh instead of mosh, sshd sits on around 7% cpu and you can't notice it updating where mosh peaks to 25%+ doing just a single ls. Directory in question has ~1000 files in it and colours are enabled for certain filetypes in case this has anything to do with it (ansi colour code processing mabe?).

**Comment by k-bx** [comment] 2015-12-10 14:25
Just wanted to mention that the problem is reproducible on latest ubuntu on scaleway arm servers (so it's easy to reproduce). Mosh has high CPU consumption and is in general slower than ssh.

**Comment by cgull** [comment] 2015-12-10 15:23
I just this week committed the code discussed in #527 and followon issues.  If you can use our Ubuntu PPAs or build from source on master, please try that.

**Comment by k-bx** [comment] 2015-12-10 16:26
@cgull ppa doesn't have anything new, but building from source seemed to solve CPU issues, thanks! Will report if I'll notice anything bad.

**Comment by andersk** [comment] 2015-12-10 18:19
@k-bx There are two PPAs. The new development is in [ppa:keithw/mosh-dev](https://launchpad.net/~keithw/+archive/ubuntu/mosh-dev).

**Comment by cgull** [comment] 2015-12-10 18:22
Closing, please open a new issue if you still have performance issues.

**Closed by cgull** 2015-12-10 18:22 UTC
Labels: bug, FreeBSD

**Comment by nvx** [comment] 2015-12-11 01:58
Is this expected to fix the high CPU on FreeBSD as this ticket is for? Or only Ubuntu?

Would rather it get tested on FreeBSD (I'm not in a position to test from source at the moment, but can update once it's in ports easily enough) before this gets unceremoniously closed because an issue on Ubuntu + ARM got fixed (despite Ubuntu + x86 not being affected, while this issue is for x86 FreeBSD...).

**Comment by cgull** [comment] 2015-12-11 02:13
FreeBSD and OS X are my primary development platforms; I did much of my profiling/analysis on FreeBSD.  The changes are mostly algorithmic and make significant improvements on all platforms; FreeBSD shows *more* relative improvement than Linux (but was slower to begin with).

**Comment by nvx** [comment] 2015-12-11 07:47
Ah very good. Initial reading of the pull request was unclear. I look forward to 1.2.6 which I assume will contain these improvements! :+1:
