### ISSUE TITLE
extra newlines on startup and exit

### ISSUE THREAD

**Issue by cgull** [mobile-shell/mosh#788] opened 2016-08-12 15:47 UTC
2016-07-31 11:47:19     mva     by the way, mosh inserting some empty lines: in the shell, it is opening, the first line is empty, and all the output (including shell prompt) starting from second line. And after detaching there is also few empty lines between local command prompt with "mosh" command and "mosh is exiting" line
2016-07-31 11:48:29     mva     it adds some aesthetic discomfort :)
2016-08-01 01:11:17     cgull   mva:  I didn't notice your mention of odd start/stop behavior before, sorry.  Mosh uses alternate-screen mode by default, and it should start with a blank screen with a shell prompt on the first line.  It switches back to the normal screen mode on exit, and that should restore the screen as it was before Mosh, with a prompt and cursor on the next line.  Trying it now, I see what I expect on startup, but there
2016-08-01 01:11:17     cgull   are two extra blank lines on exit.  Can you get screenshots of what you're seeing and post them somewhere or open a Github issue?
2016-08-01 01:35:59     mva     cgull: how about screencast?
2016-08-01 01:36:31     cgull   that'd do nicely too.
2016-08-01 01:37:22     cgull   though I'm behind some very slow connectivity right now, might take a little while to download.  And I really should be going to sleep :)
2016-08-01 01:38:39     mva     there is 1.7M
2016-08-01 01:38:51     mva     not that much bigger than few screenshots ;)
2016-08-01 01:40:07     mva     https://mva.name/files/myscreencast.mp4
2016-08-01 01:51:57     mva     didn't you already went to sleep? :)
2016-08-01 02:00:15     cgull   And yet...and yet, I'm still awake.  I see your extra line at startup.  I don't see that locally.  I see your extra two lines at exit.  I do see that locally.  I'll look at it more tomorrow.  I'm really going to sleep now.  :)
2016-08-01 02:03:44     mva     good night :)

**Comment by cgull** [comment] 2016-08-15 04:01
I've now come up with two solutions to this problem, one kludgy and low-impact (`cleanup-newlines` branch, edit some blank lines out on output), and another that I think is a more correct solution but has some potential for problems (`no-pty` branch, don't use a pty for ssh, so we don't have echo on the ssh server and don't need to output a newline to deal with that).

I now feel more strongly that Mosh shouldn't be using a pty for ssh because of this issue.  But since shells will behave differently based on whether they have a tty or not, this will certainly change (and possibly break) Mosh's behavior for some people.

Also as I write this, I remember that there's a problem on OS X with `no-pty` that I need to look at, mosh-server crashes or exits or something if it gets typeahead.  So that's not final.

**Comment by keithw** [comment] 2016-08-15 04:12
Unfortunately mosh-server required a pty (to get the initial width and height of the terminal) until 1.2.5. I would rather not break compatibility here if we can avoid it.

**Comment by sfzhi** [comment] 2017-03-28 15:03
I think this should be re-opened. The problem still exists in mosh-1.3.0.

**Comment by andersk** [comment] 2017-03-29 00:44
Both of the newlines outside the alternate-screen session come from the `puts("\r\n")` in 39ea3d9512f0fcb2457b8a20635b8c6ea9bcfe67, since `puts` appends its own newline. I think one of these is intentional and the other is not. They only show up without `--no-ssh-pty`.

The newline inside the alternate-screen session comes from 1de6575e599ef9f7c7a48a16d31d2422490eefd9, perhaps due to the kernel’s tty echo.

**Comment by cgull** [comment] 2017-03-29 04:06
Yeah,  I confess I wanted that bug to be fixed a little more than it actually was, and now I see I also missed the inside-Mosh-session problem, too.

I have a fix for the outer problem in progress.  I'm not sure @andersk's explanation for the inner problem is correct-- that newline should never reach Mosh-- but I'll have a look at it.

**Comment by andersk** [comment] 2017-03-29 04:24
I did test that replacing the `swrite( host_fd, "\n", 1 )` with `swrite( host_fd, "asdf\n", 5 )` results in the `asdf` being both displayed on the inner terminal and read into `linebuf`. The only explanation that comes to mind is tty echo.

**Comment by cgull** [comment] 2017-03-29 04:36
You're right.  This is trickier to solve cleanly; the simplest thing would be to back out 1de6575.

**Comment by andersk** [comment] 2017-03-29 04:46
We could move this parent-child communication from the pty to a separate pipe? Or maybe we could just delay the `forkpty` until that point.

**Comment by cgull** [comment] 2017-03-29 04:55
A separate pipe is what I'm working on, but...added complexity for small benefit.  Moving the `forkpty()` means we do it after networking is started, and after the clean cut-point for privilege revocation we have now.

**Comment by jasoneveleth** [comment] 2021-03-18 00:10
I'm on macOS Big Sur, and I love mosh and use it to connect to various linux boxes. Is there a hack/patch I can use to prevent the extra newlines?

**Comment by achernya** [comment] 2023-01-22 21:01
I'm marking this as a duplicate of #1142 (which is newer than this issue, but I noticed it first before doing more research).

**Closed by achernya** 2023-01-22 21:01 UTC
